### ISSUE TITLE
Faster validate function

### ISSUE THREAD

**Issue by casperlamboo** [hmeyer/stl_io#10]
I've been using this library with great pleasure, and have made heavy use of the `validate` functionality. However when using this function for larger models (4mil tris) this function becomes extremely slow. That is because the `validate` function runs in `O(n^2)`. If we were to only check on indices, instead of vertex location we could improve this function to run in linear time, see example below.

```rust
pub fn validate(indexed_mesh: &stl_io::IndexedMesh) -> Result<(), std::io::Error> {
    let mut unconnected_edges: HashMap<(usize, usize), (usize, usize, usize)> = HashMap::new();

    for (fi, face) in indexed_mesh.faces.iter().enumerate() {
        for i in 0..3 {
            let u = face.vertices[i];
            let v = face.vertices[(i + 1) % 3];
            // Verify that all vertices are different.
            if indexed_mesh.vertices[u].approx_eq(&indexed_mesh.vertices[v], F32Margin::default(),) {
                return Err(::std::io::Error::new(
                    ::std::io::ErrorKind::InvalidData,
                    format!(
                        "face #{} has identical vertices #v{} and #v{}",
                        fi,
                        i,
                        (i + 1) % 3
                    ),
                ));
            }

            if unconnected_edges.contains_key(&(v, u)) {
                unconnected_edges.remove(&(v, u));
            } else {
                unconnected_edges.insert((u, v), (fi, i, (i + 1) % 3));
            }
        }
    }

    if let Option::Some((fi, i1, i2)) = unconnected_edges.values().into_iter().next() {
        Err(::std::io::Error::new(
            ::std::io::ErrorKind::InvalidData,
            format!(
                "did not find facing edge for face #{}, edge #v{} -> #v{}",
                fi,
                i1,
                i2
            ),
        ))
    } else {
        Ok(())
    }
}
```

Would you accept a pull request for this? alternatively, if you would really like to keep the point location checking (instead of indices checking) I believe we can do some thing similar using trees that would run in `O(n log n)` but that would be a bit more complex.

**Comment by hmeyer** [comment]
Sure, sounds good to me.
Can you validate this is faster on your dataset?

**Comment by casperlamboo** [comment]
Surething! see attached table. I skipped files that contain `> 10` tris, as it already took a long time. The original method is a bit stricter then the new one. So in theory you could have instances where the new method would say a mesh is valid while the original method would not.. how ever in my data set i could not find such cases.

<details>
<summary>Results</summary>

| num tris | err (new method) | new time (ms) | err (orig method) | orig time (ms) |
|----------|------------------|---------------|-------------------|----------------|
810000|valid|296|skip due size|-
2500|valid|0|valid|817
708|valid|0|valid|59
851|valid|0|valid|100
1887|in-valid (Custom { kind: InvalidData, error: "did not find facing edge for face #1930, edge #v2 -> #v0" })|0|in-valid (Custom { kind: InvalidData, error: "did not find facing edge for face #13, edge #v1 -> #v2" })|0
3235|valid|1|valid|1207
142371|in-valid (Custom { kind: InvalidData, error: "did not find facing edge for face #321242, edge #v1 -> #v2" })|73|skip due size|-
2502|valid|1|valid|749
79072|valid|32|skip due size|-
182|valid|0|valid|3
91144|valid|42|skip due size|-
1016|valid|0|valid|119
4513|valid|1|valid|2257
750|valid|0|valid|65
98874|valid|39|skip due size|-
1953|valid|0|valid|508
59148|in-valid (Custom { kind: InvalidData, error: "face #117625 has identical vertices #v0 and #v1" })|35|skip due size|-
208|valid|0|valid|4
27152|valid|10|skip due size|-
66201|in-valid (Custom { kind: InvalidData, error: "face #503 has identical vertices #v1 and #v2" })|0|skip due size|-
2500|valid|0|valid|705
210875|valid|76|skip due size|-
18891|valid|6|skip due size|-
5132|valid|1|valid|2925
4851|valid|1|valid|2757
2055|valid|0|valid|478
2155617|valid|804|skip due size|-
18884|valid|6|skip due size|-
71930|valid|29|skip due size|-
2502|valid|1|valid|748
90035|valid|41|skip due size|-
44360|valid|17|skip due size|-
2277|valid|0|valid|613
73361|valid|25|skip due size|-
2490|valid|1|valid|776
2522|valid|1|valid|764
752|valid|0|valid|67
9245|valid|3|valid|9305
293672|valid|110|skip due size|-
192231|valid|159|skip due size|-
159312|valid|56|skip due size|-
8146|in-valid (Custom { kind: InvalidData, error: "did not find facing edge for face #1398, edge #v0 -> #v1" })|3|in-valid (Custom { kind: InvalidData, error: "did not find facing edge for face #52, edge #v1 -> #v2" })|10
6177|valid|2|valid|4734
143|valid|0|valid|2
580|valid|0|valid|40
5256|in-valid (Custom { kind: InvalidData, error: "face #10341 has identical vertices #v1 and #v2" })|1|in-valid (Custom { kind: InvalidData, error: "face #10341 has identical vertices #v1 and #v2" })|3116
666|valid|0|valid|51
2488|valid|1|valid|777
2519|valid|1|valid|826
2486|valid|1|valid|807
42105|valid|20|skip due size|-
106315|valid|54|skip due size|-
65431|in-valid (Custom { kind: InvalidData, error: "face #2439 has identical vertices #v2 and #v0" })|0|skip due size|-
53054|valid|32|skip due size|-
80276|valid|35|skip due size|-
5243|in-valid (Custom { kind: InvalidData, error: "face #10321 has identical vertices #v1 and #v2" })|2|in-valid (Custom { kind: InvalidData, error: "face #10321 has identical vertices #v1 and #v2" })|3135
686|valid|0|valid|54
7236|valid|2|valid|6477
119|valid|0|valid|1
56386|valid|24|skip due size|-
70|valid|0|valid|1
333727|valid|132|skip due size|-
48212|in-valid (Custom { kind: InvalidData, error: "face #96409 has identical vertices #v2 and #v0" })|18|skip due size|-
632|valid|0|valid|47
502683|valid|197|skip due size|-
260|valid|0|valid|7
20327|valid|7|skip due size|-
266051|in-valid (Custom { kind: InvalidData, error: "did not find facing edge for face #135, edge #v0 -> #v1" })|226|skip due size|-
241607|valid|88|skip due size|-
61248|valid|24|skip due size|-
25040|valid|12|skip due size|-
185|valid|0|valid|3
8014|valid|2|valid|7281
893119|valid|337|skip due size|-
1955|valid|0|valid|441
78|valid|0|valid|0
2049|valid|0|valid|532
61378|valid|22|skip due size|-
32072|valid|15|skip due size|-
655980|valid|323|skip due size|-
1287|valid|0|valid|201
55559|valid|28|skip due size|-
81791|in-valid (Custom { kind: InvalidData, error: "face #157762 has identical vertices #v1 and #v2" })|57|skip due size|-
202|valid|0|valid|5
204|valid|0|valid|5
34834|valid|16|skip due size|-
212634|valid|78|skip due size|-
112570|in-valid (Custom { kind: InvalidData, error: "face #27818 has identical vertices #v1 and #v2" })|5|skip due size|-
29239|valid|12|skip due size|-
2003932|valid|980|skip due size|-
1733|valid|0|valid|351
5096|valid|1|valid|3194
597380|valid|478|skip due size|-
12110|in-valid (Custom { kind: InvalidData, error: "face #6660 has identical vertices #v0 and #v1" })|1|skip due size|-
4930|valid|1|valid|2946
2006|valid|0|valid|465
2500|valid|0|valid|805
109570|valid|36|skip due size|-
2575|valid|0|valid|829
5000|valid|2|valid|3131
6154|in-valid (Custom { kind: InvalidData, error: "face #9796 has identical vertices #v1 and #v2" })|1|in-valid (Custom { kind: InvalidData, error: "face #9796 has identical vertices #v1 and #v2" })|2825
29907|valid|12|skip due size|-
576|valid|0|valid|38
2372|valid|0|valid|804
47972|in-valid (Custom { kind: InvalidData, error: "face #81 has identical vertices #v1 and #v2" })|0|skip due size|-
356|valid|0|valid|13
1946|valid|0|valid|447
90369|valid|33|skip due size|-
1759|valid|0|valid|363
46537|valid|17|skip due size|-
1956|valid|0|valid|441
22921|in-valid (Custom { kind: InvalidData, error: "face #3129 has identical vertices #v0 and #v1" })|0|skip due size|-
43691|valid|16|skip due size|-
628|valid|0|valid|45
2503|valid|0|valid|763
39172|valid|19|skip due size|-
224|valid|0|valid|6
746|valid|0|valid|62
137098|valid|55|skip due size|-
584|valid|0|valid|39
452|in-valid (Custom { kind: InvalidData, error: "did not find facing edge for face #848, edge #v1 -> #v2" })|0|in-valid (Custom { kind: InvalidData, error: "did not find facing edge for face #20, edge #v1 -> #v2" })|0
697|valid|0|valid|53
9769|valid|4|valid|11173
1841|valid|0|valid|401
230091|valid|85|skip due size|-
16944|valid|7|skip due size|-
2436|valid|0|valid|806
36854|in-valid (Custom { kind: InvalidData, error: "face #4063 has identical vertices #v2 and #v0" })|0|skip due size|-
67761|in-valid (Custom { kind: InvalidData, error: "did not find facing edge for face #29760, edge #v2 -> #v0" })|29|skip due size|-
460590|valid|211|skip due size|-
58|valid|0|valid|0
11982|valid|4|skip due size|-
30954|in-valid (Custom { kind: InvalidData, error: "face #54055 has identical vertices #v2 and #v0" })|10|skip due size|-
258609|valid|95|skip due size|-
704|valid|0|valid|56
67003|in-valid (Custom { kind: InvalidData, error: "did not find facing edge for face #117067, edge #v1 -> #v2" })|28|skip due size|-
597|valid|0|valid|39
2502|valid|0|valid|807
131141|valid|46|skip due size|-
22295|in-valid (Custom { kind: InvalidData, error: "did not find facing edge for face #44509, edge #v2 -> #v0" })|9|skip due size|-
45013|in-valid (Custom { kind: InvalidData, error: "face #135 has identical vertices #v1 and #v2" })|0|skip due size|-
2502|valid|0|valid|762
177754|valid|66|skip due size|-
3609600|valid|1433|skip due size|-
31209|in-valid (Custom { kind: InvalidData, error: "face #54180 has identical vertices #v1 and #v2" })|10|skip due size|-
231441|valid|83|skip due size|-
478704|valid|498|skip due size|-
202794|valid|76|skip due size|-
66274|in-valid (Custom { kind: InvalidData, error: "face #182 has identical vertices #v2 and #v0" })|0|skip due size|-
221|valid|0|valid|6
18216|valid|6|skip due size|-
391541|valid|176|skip due size|-
2484|valid|1|valid|786
83865|valid|52|skip due size|-
7640|valid|2|valid|6793
204|valid|0|valid|5
15319|in-valid (Custom { kind: InvalidData, error: "face #29181 has identical vertices #v2 and #v0" })|5|skip due size|-
21144|valid|8|skip due size|-
356|valid|0|valid|14
27742|valid|9|skip due size|-
67135|in-valid (Custom { kind: InvalidData, error: "face #241 has identical vertices #v2 and #v0" })|0|skip due size|-
628|valid|0|valid|45
2508|valid|1|valid|712
724742|valid|538|skip due size|-
72924|in-valid (Custom { kind: InvalidData, error: "did not find facing edge for face #178573, edge #v1 -> #v2" })|39|skip due size|-
570180|valid|219|skip due size|-
2500|valid|1|valid|800
8196|valid|3|valid|8738
778290|in-valid (Custom { kind: InvalidData, error: "did not find facing edge for face #113496, edge #v1 -> #v2" })|664|skip due size|-
9912|valid|3|valid|11575
1200|valid|0|valid|176
1068|valid|0|valid|130
922|valid|0|valid|99
468|valid|0|valid|26
2496|valid|0|valid|793
71017|valid|34|skip due size|-
2531|valid|1|valid|825
688|valid|0|valid|54
50085|valid|25|skip due size|-
17932|valid|5|skip due size|-
28125|in-valid (Custom { kind: InvalidData, error: "face #53942 has identical vertices #v1 and #v2" })|9|skip due size|-
1104470|valid|434|skip due size|-
400|valid|0|valid|17
6776|valid|2|valid|5196
1425|valid|0|valid|228
221|valid|0|valid|5
41324|in-valid (Custom { kind: InvalidData, error: "face #9202 has identical vertices #v2 and #v0" })|1|skip due size|-
10044|valid|3|skip due size|-
1064|valid|0|valid|133
1197739|in-valid (Custom { kind: InvalidData, error: "did not find facing edge for face #1807569, edge #v0 -> #v1" })|611|skip due size|-
12249|valid|4|skip due size|-
2502|valid|1|valid|780
71930|valid|29|skip due size|-
14586|in-valid (Custom { kind: InvalidData, error: "face #27785 has identical vertices #v1 and #v2" })|4|skip due size|-
512445|valid|193|skip due size|-
2006|valid|0|valid|465
176|valid|0|valid|3
27820|in-valid (Custom { kind: InvalidData, error: "face #53625 has identical vertices #v2 and #v0" })|9|skip due size|-
668|valid|0|valid|52
40131|valid|15|skip due size|-
119|valid|0|valid|1
36048|valid|15|skip due size|-
135624|valid|89|skip due size|-
</details>

**Comment by hmeyer** [comment]
>> The original method is a bit stricter then the new one.
Can you please elaborate?

**Comment by casperlamboo** [comment]
The original model check for vertex positions, and the new method only checks vertex indices. If there were two adjacent triangles (triangle `a` and `b`) that would share an edge. But both edges only don't use the same indices, but their indices correspond to the same vertex location, then the new method would state that that the input model is invalid while the new method would see that the actual vertices overlap.

**Comment by hmeyer** [comment]
I see. I think that is a plus. So feel free to go ahead and send a PR.

**Comment by casperlamboo** [comment]
If that is considered a plus i will also update
```rust
            if indexed_mesh.vertices[u].approx_eq(&indexed_mesh.vertices[v], F32Margin::default(),) {
```
to be
```rust
           if u != v {
```
If that is alright? (also benefits consistency)

**Comment by hmeyer** [comment]
> If that is considered a plus i will also update
> 
> ```rust
>             if indexed_mesh.vertices[u].approx_eq(&indexed_mesh.vertices[v], F32Margin::default(),) {
> ```
> 
> to
> 
> ```rust
>            if u == v {
> ```
> 
> If that is alright? (also benefits consistency)

I think those are separate things.
This check:
> ```rust
>             if indexed_mesh.vertices[u].approx_eq(&indexed_mesh.vertices[v], F32Margin::default(),) {
> ```
Confirms that two vertices of a face a distinct in space. Having them different vertices, could still mean they are identical in space.

The other check confirmed that two edges were adjacent in space. Which is approximately right.
But it is better to confirm the are exactly adjacent by using the identical vertices.

**Comment by casperlamboo** [comment]
Hi yes you are right. However this is is (semantically) the same that is made for the unconnected faces check. For consistency i wanted to make them the same.

But i see what you mean that this check would also detect 0-area faces. My method would not catch these cases.

But can i then propose an actual tri- area check, and reject if the area is 0? This way a face with 3 collinear points is also rejected.

**Comment by hmeyer** [comment]
Oh yes. Good idea.

Casper Lamboo ***@***.***> schrieb am Do., 6. Mai 2021, 05:52:

**Comment by casperlamboo** [comment]
Just updated my pull request. What do you think about the macro vector operation solution? not super pretty but didn't want to add a whole math vector decency to this library.

I also added some tests to make sure that the triangle calculations were correct.
